### ISSUE TITLE
Mac compatible binaries

### ISSUE THREAD

**Issue by perguth** [oniony/TMSU#75]
... would be nice. Currently I get `exec format error: tmsu` on 2,7 GHz Intel Core i5, ~~Crap~~MacOS 10.11.4.

**Comment by oniony** [comment]
Hi, thanks for raising this.

Unfortunately I don't have an Mac O/S environment with which to do this. I have seen reports that TMSU will build from source now on Mac, so that might be worth a try?

**Comment by pguth** [comment]
Yeah, I am going to try.

**Comment by pguth** [comment]
Works on 10.11.5! Following the Linux steps in [https://github.com/oniony/TMSU/blob/master/COMPILING.md]().

**Comment by pguth** [comment]
But:
```sh
➜  ~ tmsu mount
tmsu: invalid subcommand 'mount'
```

**Comment by oniony** [comment]
Great news you got it compiling on Mac. Regarding the `mount` subcommand: it's because the `https://github.com/oniony/TMSU/blob/master/src/github.com/oniony/TMSU/cli/commands_darwin.go` file exists. You could try removing this file and recompiling to see if the FUSE level stuff works.

**Comment by pguth** [comment]
Just deleting does not work:
```sh
src/github.com/oniony/TMSU/cli/cli.go:28: undefined: commands
src/github.com/oniony/TMSU/cli/cli.go:30: undefined: commands
src/github.com/oniony/TMSU/cli/cli.go:38: undefined: commands
src/github.com/oniony/TMSU/cli/cli.go:40: undefined: commands
```

Just copying stuff from `commands.go` does yield:
```sh
src/github.com/oniony/TMSU/cli/commands_darwin.go:33: undefined: MountCommand
src/github.com/oniony/TMSU/cli/commands_darwin.go:39: undefined: UnmountCommand
src/github.com/oniony/TMSU/cli/commands_darwin.go:44: undefined: VfsCommand
```

**Comment by oniony** [comment]
My appologies. In addition to deleting the file, you will also need to adjust this line in `commands.go`:

    // +build !windows,!darwin

Remove the `,!darwin` from the end, to include the building of this file.

**Comment by pguth** [comment]
Ok, did that. Same result:
```sh
src/github.com/oniony/TMSU/cli/commands.go:33: undefined: MountCommand
src/github.com/oniony/TMSU/cli/commands.go:39: undefined: UnmountCommand
src/github.com/oniony/TMSU/cli/commands.go:44: undefined: VfsCommand
```

**Comment by oniony** [comment]
Very strange. May I ask what command you are running to build it?

**Comment by pguth** [comment]
Overall:
```sh
go get -u github.com/mattn/go-sqlite3
go get -u github.com/hanwen/go-fuse/fuse
make
sudo make install
```
With:
```sh
➜  TMSU git:(master) ✗ echo $PATH
/Users/user/.nvm/versions/node/v6.1.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/user/.npm/bin:/usr/local/go/bin
➜  TMSU git:(master) ✗ echo $GOPATH
/Users/user/.go
➜  TMSU git:(master) ✗ tree -d /Users/user/.go
/Users/user/.go
├── pkg
│   └── darwin_amd64
│       └── github.com
│           ├── hanwen
│           │   └── go-fuse
│           └── mattn
└── src
    └── github.com
        ├── hanwen
        │   └── go-fuse
        │       ├── benchmark
        │       ├── example
        │       │   ├── autounionfs
        │       │   ├── hello
        │       │   ├── loopback
        │       │   ├── memfs
        │       │   ├── multizip
        │       │   ├── statfs
        │       │   ├── unionfs
        │       │   └── zipfs
        │       ├── fuse
        │       │   ├── nodefs
        │       │   ├── pathfs
        │       │   └── test
        │       ├── splice
        │       ├── unionfs
        │       └── zipfs
        └── mattn
            └── go-sqlite3
                ├── _example
                │   ├── custom_func
                │   ├── hook
                │   ├── mod_regexp
                │   ├── mod_vtable
                │   └── simple
                └── sqlite3_test

36 directories
```

**Comment by oniony** [comment]
OK, it turns out I'm an idiot. You have to also remove the `!darwin` bits from those three files: `mount.go`, `unmount.go`, `vfs.go`.

**Comment by oniony** [comment]
Also `fusevfs.go` and `mtable.go` in the `src/github.com/oniony/TMSU/vfs` directory.

**Comment by pguth** [comment]
Got it to work, :cake:! See oniony/TMSU/pull/76

Compilation results, MacOS 10.11.5: [Archive.zip](https://github.com/oniony/TMSU/files/283040/Archive.zip)
